version: "3"
services:
  app:
    build: .
    command: >
      sh -c "rm -f tmp/pids/server.pid &&
      rails db:setup &&
      bundle exec rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
